parameters:
  - name: hdf5tag
    default: hdf5-1_10_7
  - name: extraflags
    default: ''
  - name: gui
    default: true
  - name: threading
    default: true
  - name: qtver
    default: 6.2.2

steps:
  - bash: |
      set -ex
      brew update-reset
      brew install ninja
      pip3 install pyinstaller
      pip3 install flask
      pip3 install h5py
      pip3 install lxml
      # -- Qt
      sudo pip3 install conan aqtinstall
      aqt install-qt --outputdir /tmp/qt mac desktop ${{ parameters.qtver }} -m qtcharts
    displayName: 'Install Prerequisites'
  - bash: |
      wget https://github.com/disorderedmaterials/HDF5/releases/download/${{ parameters.hdf5tag }}/${{ parameters.hdf5tag }}-osx.zip
      unzip ${{ parameters.hdf5tag }}-osx.zip
      ls
    displayName: 'Download HDF5 Artifacts'
  - bash: |
      set -ex
      HDF5_DIR="$(pwd)/${{ parameters.hdf5tag }}"
      # Managing packages
      Qt6_DIR=/tmp/qt/${{ parameters.qtver }}/macos/lib/cmake/Qt6
      QT_BASE_DIR=/tmp/qt/${{ parameters.qtver }}/macos
      QTVER=${{ parameters.qtver }}
      # Building
      mkdir build
      cd build
      conan install .. --build missing
      cmake -DGUI:bool=true ${{ parameters.extraflags }} -DQT_BASE_DIR=$QT_BASE_DIR ../
      make

      cd ../
      pyinstaller backend/isisInternal.py
      pyinstaller backend/jv2Setup.py
    displayName: 'Build'